### ISSUE TITLE
Getting Job ID	

### ISSUE THREAD

**Issue by ckapitzke** [wirecard/paymentSDK-Android#6]
Hello again,

how can get the wirecard "Job ID" out of the response from a payment response?

best regards, 
Christian

**Comment by stefan-sedlak** [comment]
Hi @ckapitzke,

what do you mean by Job ID?
There is only [transactionId](http://paymentsdk.github.io/classde_1_1wirecard_1_1paymentsdk_1_1_wirecard_payment_response.html#ae8693d45e14a6d793aca473824755f7c), what can be used as an identifier.
MerchantAccountID+RequestID is as well unique, because RequestID shall be generated on your server side.

Best,
Stefan

**Comment by ckapitzke** [comment]
Hi @stefan-sedlak 
thanks for your reply. I'm not sure how i can describe it. 
Using the web api there is a field called OrderNumber which contains this Wirecard JobID. this is **not** the transaction id and not the shop order id.

**Comment by stefan-sedlak** [comment]
Hi @ckapitzke 
I did an investigation, but I did not find "Job ID" in paymentSDK-Android backend gateway.
Could you please send a web API doc link? It could help me to say if Android SDK supports the feature.

Anyway Order/Order number is not parsed by Android SDK from response. It was not needed until now.

Best,
Stefan

**Comment by ckapitzke** [comment]
hi @stefan-sedlak 
of course: https://guides.wirecard.at/rest_api?s[]=ordernumber 
search for "Final transaction results"

**Comment by stefan-sedlak** [comment]
Now it make sense.
You use checkout page provided by Wirecard CEE.
paymentSDK-Android is intended for Wirecard Payment [Gateway](https://document-center.wirecard.com/display/PTD)

Best,
Stefan
